### ISSUE TITLE
left/right mask not showing up on vertical panels

### ISSUE THREAD

**Issue by jacqui** [ajam/pulp#33]
I was trying to figure out why some of the panels weren't masked correctly in the latest page art I got from our artist - basically, the transitions work but you can see all the surrounding stuff on the right and left of each panel from one transition to the next.

Spelunking in the CSS led me to find that the z-index on the #left-mask and #right-mask divs wasn't high enough. I don't full get why this is, but I know that when I changed the z-index value from '999' to '9999' (yo, add a 9 to it) the masks and panels looked great.

This is only an issue for me now with vertical not horizontal panels. I will submit a pull request once I test it out a bit more, but I wanted to log it as an issue. Figured you'd have a better understanding of what's going on here than I do.

One more thing: pulp & pulp-viewer are amazing and everyone at BBC News (myself included) LOVES it. So... thank you :)

**Comment by mhkeller** [comment]
Thanks Jacqui! AKA code spelunking extraordinaire. 
![code-spelunking](https://cloud.githubusercontent.com/assets/498744/6755100/322ce5be-cef7-11e4-9f01-e43f1940c5f8.png)

I think the pull request has to include `"(yo, add a 9 to it)"`. We might want to throw a 9 on [`#btns`](https://github.com/ajam/pulp/blob/master/css/styles.styl#L352) too so they remain on top of everything and don't get masked. The masks and buttons shouldn't ever really coexist, however, since one is mobile and the other desktop but #34 might change this in the future.
