### ISSUE TITLE
Recommended resolution for pages images ?

### ISSUE THREAD

**Issue by nylnook** [ajam/pulp#37]
Hi, and first of all, thanks for this amazing tool and the work behind ! 

I'm investigating Pulp for a comic project, and I was wondering what is the workflow for creating pages, and specially the web to print (or reverse)...
In the demo jpg files have a 1145x1500 pixel size, which is close to an "US letter" aspect-ratio, but not exactly... and not close to a printed comic book, neither an A4 format.

So, how did you choose this size in particular ?
Will another aspect-ratio work with pulp ? I believe the answer is yes because it's responsive, but I don't know every details... 

I could have investigated the terms of service repository, but it seem to have been retired of Github...

Thanks in advance !

**Comment by mhkeller** [comment]
Hi @nylnook, for some reason I didn't get an email about this issue being created.

It should fit any size image. We went with that aspect ratio since it fit iPads best and Josh had done another digital comic at that aspect ratio. The SF Public Press went with a different one though: http://sfpublicpress.org/graphics/traumatized/#1

Let me know what you end up finding. In terms of responsiveness, it measures how one page will fit fitting into the vertical space and then sees if it can fit two pages at that size to do the double layout. So it's all based on the dimensions of the input images.

**Comment by nylnook** [comment]
Hi @mhkeller ! No worries, I'm not in a hurry.

Thanks for this feedback... I'll do some extensive testing next week and let you know what I can discover ;)

**Comment by nylnook** [comment]
Hi,
after a lot of testing, every image size I tested worked with Pulp ;)

I will keep the "A" paper format... with Pulp on an iPad tablet resolution (1024x768), two pages are displayed if the tablet is horizontal, and one if it's vertical, and very few lost margins.

For the record, I will use a slightly over-sized A5 (210x148mm + crop margins) at 600 dpi as a source for printing, and export the croped A5 image at 175 dpi to get a 1021x1449px jpg page for the web.

Choosing a small print format like A5 allow me to avoid font size mismatches between print and screen (using an A4, a 12pt font size would probably be too small once exported on screen).

I suppose there is no straight answer to this question... it depends of your print expectations ;)

My best regards !

**Comment by mhkeller** [comment]
Good to hear! I'll add a link to this thread in the readme so people can find it.

**Comment by nylnook** [comment]
I would be honored :smile:

**Comment by mhkeller** [comment]
Done. https://github.com/ajam/pulp#choosing-an-image-format Let me know when you're project is out and I'll add it to the "In the wild" section

**Comment by nylnook** [comment]
I will, thanks again !
